stages:
  - build
  - test
  - stage
  - deploy

pages:
  stage: stage
  script:
  - mkdir .public
  - cp -r src/FamilyTree.FrontendDraft/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  environment: 
    name: pages
    url: $CI_PAGES_URL
  only:
  - frontend

build:
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}:dev"
  services:
    - docker:dind
  stage: build
  before_script:
    - docker info
  script:
    - sh build-docker-image.sh
    - docker login -p ${CI_REGISTRY_PASSWORD} -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - docker push ${IMAGE_NAME}
  only:
  - development
  - ci-setup
