version: "3"

services:
  db-master:
    image: postgres:11.2
    environment:
      POSTGRES_PASSWORD: wiki
      POSTGRES_DB: wiki
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  db-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "wiki"
      PGADMIN_DEFAULT_PASSWORD: "wiki"
    depends_on:
      - db-master
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - .\servers.json:/pgadmin4/servers.json
    networks:
      - default

  wiki:
    image: "${CI_REGISTRY_IMAGE}"
    labels:
      traefik.docker.network: "traefik_proxy"
      traefik.enable: "true"
      traefik.frontend.rule: Host:${CI_DEPLOYMENT_URL}
      traefik.port: 80
    depends_on:
      - db-master
    networks:
      - default
      - traefik_proxy

volumes:
  postgres-data:
  pgadmin-data:

networks:
  default:
  traefik_proxy:
    external: true
    external: true
